### PR TITLE
eoxcloudless as BYOA into public collections

### PR DESCRIPTION
**Pull request by Scartography**
* dont know if the custom key: https://github.com/eurodatacube/public-collections/blob/update_eoxcloudless_to_byoa/collections/eoxcloudless-s2-global-mosaic-10.yaml#L17-L19 will work like this
* also merge after launching the BYOA at EDC

### CODE REVIEW

**Comment by Scartography** [comment]
Moved the price information into additional information readme.md

**Comment by Schpidi** [comment]
@Dorothyrono this is now ready to be merged and deployed. Does a merge trigger an automatic deploy or is there a manual step needed? Thanks.

**Review by Schpidi — APPROVED** [review]

**Comment by Dorothyrono** [comment]
@Schpidi  yes, merging  triggers  an automatic deploy.  

but the changes can take upto max 1 hr to take effect .  

but after merging,  you can check the changes after  2 mins or so  under :

https://s3.eu-central-1.amazonaws.com/collections.eurodatacube.com/eoxcloudless-s2-global-mosaic-10/index.html
https://s3.eu-central-1.amazonaws.com/collections.eurodatacube.com/eoxcloudless-s2-global-mosaic-10/readme.html

**Comment by dthiex** [comment]
> 
> 
> @Schpidi do you mean automatic deploy on EDC browser ?
> 
> Most probably so,,
> 
> but @dthiex can give a sure confirmation

The collection will be automatically available at `https://collections.eurodatacube.com/` after the merge.

As collection within the EDC Browser it will also be available automatically (though only if we are able to create a STAC compliant JSON from the YAML file). As there are some mandatory metadata fields missing in the YAML file this will not happen until those are added.

**Comment by Schpidi** [comment]
We tested locally that nothing breaks and as the change only affects one collection we added I'm going to merge and see what happens.

**Comment by Schpidi** [comment]
@dthiex thanks for the details. we need it in the "On demand data" tab of the EDC browser, there it should be fine.

how long does the deploy typically take? I see that the old images are not available anymore at https://collections.eurodatacube.com/eoxcloudless-s2-global-mosaic-10/readme.html and the new ones are there like https://collections.eurodatacube.com/eoxcloudless-s2-global-mosaic-10/S2cloudless-2020_website_smaller.jpg but the text is not yet updated. thanks for your help.

**Comment by Schpidi** [comment]
is there maybe an invalidation step missing on the cloudfront distribution? we use this in the dashboard https://github.com/eurodatacube/eodash/blob/staging/.github/workflows/production_deploy.yml#L52

**Comment by Dorothyrono** [comment]
> how long does the deploy typically take?

 normally  it takes upto 1 hr max  for all changes to be updated  . should be all updated soon @Schpidi

**Comment by Dorothyrono** [comment]
> is there maybe an invalidation step missing on the cloudfront distribution? we use this in the dashboard https://github.com/eurodatacube/eodash/blob/staging/.github/workflows/production_deploy.yml#L52

@Developer1510 , you probably are the right person to know this

**Comment by dthiex** [comment]
I just checked again and both the html as well as the collection overview page are both updated now.

**Comment by Schpidi** [comment]
confirmed, thx a lot

**Pull request merged**
