### PR TITLE
Add eoxcloudless to the collection

### PR DESCRIPTION
**Pull request by Scartography**
* the build runs through
* issues with the Additional Info `README.MD` link after building locally (https://github.com/eurodatacube/public-collections/blob/add_eoxcloudless/collections/eoxcloudless-s2-global-mosaic-10.yaml#L8)

### CODE REVIEW

**Comment by Scartography** [comment]
Also add or enable new/other resource groups to see more data options: https://github.com/eurodatacube/public-collections/blob/add_eoxcloudless/collections/eoxcloudless-s2-global-mosaic-10.yaml#L58

**Comment by Schpidi** [comment]
@Kampen1988 can you help me to build the page locally? I'm running `npm install` followed by `BASE_URL=http://0.0.0.0:8000 npm run build` to service it via `python3 -m http.server` but this doesn't render the readme pages properly. Thanks.

**Comment by Kampen1988** [comment]
## How to build the pages locally:

To build the HTML files, it uses Node.js, and a GULP JS file, which is working with Handlebars templates.

#### Set environment variables on your local.
- create `.env` file with the following content in the root folder of the repository:
```
GIT_HUB_COLLECTIONS_REPO=eurodatacube/public-collections
GIT_HUB_COLLECTIONS_BRANCH=main
COLLECTIONS_BROWSER_ROOT_URL=https://https://collections.eurodatacube.com//
COLLECTIONS_BROWSER_S3_BUCKET=s3://https://collections.eurodatacube.com//
```
- in terminal run: `export $(xargs <.env)`

#### Install node.js using nvm (skip this step if not needed)
- `wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash` or `curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash `
- exit terminal
- `nvm install node` - to install most recent node.js version.

#### Install npm (if needed)
- `npm install` -  this has to be run once

#### Running the build
- `npm run build`
- After successful build,  HTML files can be found in ./_output directory

**Comment by Schpidi** [comment]
Thanks, these env vars did the trick. I'm using the command: `GIT_HUB_COLLECTIONS_REPO=eurodatacube/public-collections GIT_HUB_COLLECTIONS_BRANCH=main COLLECTIONS_BROWSER_ROOT_URL=http://0.0.0.0:8000/ COLLECTIONS_BROWSER_S3_BUCKET=s3://https://collections.eurodatacube.com// npm run build` to build and `python3 -m http.server` to serve the files locally.

**Pull request merged**
