### PR TITLE
Update tsmn_water_quality_saturday.yaml

### PR DESCRIPTION
**Pull request by AlessandroScremin**
changed the time interval to ongoing

### CODE REVIEW

**Comment by AlessandroScremin** [comment]
Dear @chorng cc: @Schpidi @gmilcinski 

i went trough the yaml files in public collections, and I was updating the time intervals. During this change I noticed that the yaml file has an edc browser link, and also the type and collection ID and endpoint refer to old informations.

EDCBrowser: https://browser.eurodatacube.com/?zoom=7&lat=43.14975&lng=7.16013&collectionId=tsmn_water_quality_saturday&layerId=Total%20Suspended%20Matter%20Map&type=sentinel-hub-edc&fromTime=2020-04-17T00%3A00%3A00.000Z&toTime=2021-04-17T00%3A00%3A00.000Z

and
EndPoint: https://shservices.mundiwebservices.com
  Type: byoc-45ce0fb2-fdaf-481e-b834-f728a8677e59
   CollectionId: 45ce0fb2-fdaf-481e-b834-f728a8677e59


what i see is that even if the EDC browser link works the collection ID and type refer the old collections IDs(the one on mundi and not on the new ones that have been migrated.

This is valid for almost all the collections we handle. Is there a way for you to update these fields and check if the EDC Browser link is pointing to the right layer name?

the other collections that need an update of the mentioned fields are:

- [2mt_2020_monthly_average_from_cds.yaml](https://github.com/eurodatacube/public-collections/blob/main/collections/2mt_2020_monthly_average_from_cds.yaml)
- [cams_glc_2017.yaml](https://github.com/eurodatacube/public-collections/blob/main/collections/cams_glc_2017.yaml)
- [chl_water_quality_saturday.yaml](https://github.com/eurodatacube/public-collections/blob/main/collections/chl_water_quality_saturday.yaml)
- [e12c_motorway.yaml](https://github.com/eurodatacube/public-collections/blob/main/collections/e12c_motorway.yaml)
- [e12d_primary_corrected.yaml](https://github.com/eurodatacube/public-collections/blob/main/collections/e12d_primary_corrected.yaml)
- [iceye_e11.yaml](https://github.com/eurodatacube/public-collections/blob/main/collections/iceye_e11.yaml)
- [iceye_e11a.yaml](https://github.com/eurodatacube/public-collections/blob/main/collections/iceye_e11a.yaml)
- [iceye_e13b.yaml](https://github.com/eurodatacube/public-collections/blob/main/collections/iceye_e13b.yaml)
- [iceye_e3.yaml](https://github.com/eurodatacube/public-collections/blob/main/collections/iceye_e3.yaml)
- [jaxa_wq_chla.yaml](https://github.com/eurodatacube/public-collections/blob/main/collections/jaxa_wq_chla.yaml)
- [jaxa_wq_tsm.yaml](https://github.com/eurodatacube/public-collections/blob/main/collections/jaxa_wq_tsm.yaml)
- [population_density.yaml](https://github.com/eurodatacube/public-collections/blob/main/collections/population_density.yaml)
- [s5p-no2-tropno-daily-check.yaml](https://github.com/eurodatacube/public-collections/blob/main/collections/s5p-no2-tropno-daily-check.yaml)
- [tsmn_water_quality_saturday.yaml](https://github.com/eurodatacube/public-collections/blob/main/collections/tsmn_water_quality_saturday.yaml)
- [wind_10m_u.yaml](https://github.com/eurodatacube/public-collections/blob/main/collections/wind_10m_u.yaml)
[wind_10m_v.yaml](https://github.com/eurodatacube/public-collections/blob/main/collections/wind_10m_v.yaml)
 
 
 Thanks for all the support you could provide
 
 kr
 Alessandro

**Review by Schpidi — APPROVED** [review]

**Comment by chorng** [comment]
Dear @AlessandroScremin ,

There is a pull request which updates collection ids. Could you take a look at this [PR](https://github.com/eurodatacube/public-collections/pull/189) and confirm that it does what you requested.

BR,
Chung

**Comment by AlessandroScremin** [comment]
Dear @chorng 
Thanks a lot...it is what I needed. Very appreviated

Alessanadro

**Comment by dthiex** [comment]
Of the above mentioned collections almost all got update in this PR: https://github.com/eurodatacube/public-collections/pull/189

@chorng Can you please check what is with [cams_glc_2017.yaml](https://github.com/eurodatacube/public-collections/blob/main/collections/cams_glc_2017.yaml) as this one didn't get updated and is still on mundi.

**Comment by chorng** [comment]
@dthiex Max and I ingested the `cams_glc_2017` and `Jaxa-alos2-Activity-cars-containers` collections. I updated the `cams_glc_2017.yaml` with [PR 192](https://github.com/eurodatacube/public-collections/pull/192). Note that `Jaxa-alos2-Activity-cars-containers` is not included in the edc public collection atm.

**Comment by Dorothyrono** [comment]
I believe this was duly  approved

**Pull request merged**
