### PR TITLE
Docs about Field Delineation algorithm

### PR DESCRIPTION
**Pull request by AleksMat**
Submitting a documentation page about the Field Delineation BYOA that is currently being on-boarded. Any comments and suggestions are welcome.

### CODE REVIEW

**Review by totycro — APPROVED** [review]

**Comment by totycro** [comment]
@Dorothyrono These changes should now be published to collections.eurodatacube.com in order for field delineation to be published. Could you apply them there?

**Comment by Dorothyrono** [comment]
If needed soon.. @chorng  or  @Kampen1988  could help

**Comment by AleksMat** [comment]
Hi @totycro, I see that these changes have been deployed and are available at https://collections.eurodatacube.com/field-delineation/. :tada:

**Comment by totycro** [comment]
Thanks for applying the changes, the algorithm is now also available on the EDC marketplace:
https://eurodatacube.com/marketplace/data-products/on-demand

**Pull request merged**
