### PR TITLE
Added yaml and folders for the collections avaialbe in EDC 

### PR DESCRIPTION
**Pull request by AlessandroScremin**
Added yaml and folders for the collections avaialbe in EDC

### CODE REVIEW

**Comment by AlessandroScremin** [comment]
@Schpidi 
can you see this pull request???

**Comment by gmilcinski** [comment]
Hi @AlessandroScremin - @Kampen1988 is working on this merge request. There is some work required as the code you pushed is crashing the build. But are working to try to fix it.  
Just to understand the urgencies - is there a specific timeline, apart of ASAP?

**Comment by AlessandroScremin** [comment]
@gmilcinski to me the deadline was 7th May...tomorrow....I can investigate if more time is needed...will ask Anca

**Comment by Schpidi** [comment]
my understanding is that this is critical for June 1st when the challenges go live. but as we need a review cycle the idea was to have a first version for May 7th. so not super urgent but will safe panic mode later on.

**Comment by Kampen1988** [comment]
With some corrections the build worked! I can push my changes to the merge request tomorrow to have a first version online. Following this we can improve some of the descriptions as we see fit.

**Comment by AlessandroScremin** [comment]
@Kampen1988 
ok for me...but please let mw know what was wrong with the files so that next time I can avoid same errors

kr

Alessandro

**Comment by aapopescu** [comment]
@AlessandroScremin 

We need to add the trilateral JAXA WQ maps data

**Comment by AlessandroScremin** [comment]
@aapopescu 
ok I will generate them...but just to let you know Jaxa maps are not available in Race, for this reason I didn't add them to the accessible products. the tabs are only availbe for the trilateral...

see pictures to betetr understand what I mean.

image

**Comment by aapopescu** [comment]
@AlessandroScremin for the hackathon we need all the data in trilateral

**Comment by AlessandroScremin** [comment]
> @AlessandroScremin
> 
> We need to add :
> 
> * the trilateral JAXA WQ maps data and all the new data they want to make available --> @gmilcinski
> * S2 layers that are used in the E13b - airplane detections --> this one should only get the hackathon tag in the edc catalogue

SO to clarify
I added all the layers we ingested in EDC. Pleiades and Planet datasets used for archived and old products were not added. Should I add also the archived Pleiades and Planets data collections?

S2 Layers that are used for E13b, these are the default Sentinel 2 layers, so alredy in EDC. what were you referring to?

rk
Alessandro

**Comment by AlessandroScremin** [comment]
@aapopescu 

ok let me recap:

Almost all the layers we inegsted into EDC have been provided. Pleiades and Planets were excluded. Shoudl I add also those collections to the yaml file? (are mainly related to the archived ship detection, and car counts in parking lots)

E13b. THis indicator use the dafault EDC sentinel 2 layers and the geoJsons, so we didn't ingest any S2 data nor GeoJsons. SO what you had in mind with E13b S2 layers?

kr
Alessandro

**Pull request merged**
