### PR TITLE
update of description for ghsl-urban-delineation and new description for wsf-urban-delineation

### PR DESCRIPTION
**Pull request by eorlitova**
update of description for ghsl-urban-delineation and new description for wsf-urban-delineation

### CODE REVIEW

**Review by Schpidi — APPROVED** [review]
Looks good to me

**Comment by eorlitova** [comment]
Hi Stephan,
I have created a pull requests to edit description for wsf-urban-delineation
commit 20c486c9bd1161269a99c6a68f6aa492e83a2f55
for edit of ollections/wsf-urban-delineation.yaml
and
commit 4f6340a008cb44563e567971d8c3ba63cdd6a09a
for edit collections/wsf-urban-delineation/PRICING.MD

Could you please merge them into main?
Best,
Erika

**Comment by Schpidi** [comment]
Thanks, I've merged this.

Just FYI, we're still waiting for the description of the third algorithm. Note that only once the description here is available it will be visible on the marketplace.

**Comment by eorlitova** [comment]
Hi Stephan,
I have created a pull request into the public-collection with the
description of DLR Docker algorithm.
Thanks and best regards,
Erika

**Comment by Schpidi** [comment]
Hi Erika, I'm afraid I don't see a new PR. Could you please share a link to it? Thanks.

**Comment by eorlitova** [comment]
Hi Stephan,
commit details are:
https://github.com/eurodatacube/public-collections/commit/7f82565405fa90dd7f590eafc6b2e31a8d8da51f

Seems I forgot to create pull requests after committing. Is it OK now?
Erika

**Comment by Schpidi** [comment]
Thanks, I renamed the algorithm to match the name used on the BYOA side and merged the amended PR #322 .

**Pull request merged**
