### PR TITLE
updating description of ocean color datasets and lake water quality

### PR DESCRIPTION
**Pull request by AliceBalfanz**
This PR updates info about Ocean color and lake water quality datasets

### CODE REVIEW

**Comment by Dorothyrono** [comment]
@dthiex  could you please help review ?

**Review by dthiex — APPROVED** [review]
Looks good.

**Comment by AliceBalfanz** [comment]
Thanks @dthiex :) May I merge then? Or will one of you merge the PR @Dorothyrono or @dthiex ?

**Comment by dthiex** [comment]
> May I merge then?

@AliceBalfanz I merged this now so we get the changes out but next time feel free to merge the changes once you received approval on them from one of us.

**Pull request merged**
