### PR TITLE
adding description of mci

### PR DESCRIPTION
**Pull request by AliceBalfanz**
Dear @Dorothyrono , I would be very grateful if you would find time soon to take a look at this PR :) Thank you very much!

### CODE REVIEW

**Comment by Schpidi** [comment]
Thanks @AliceBalfanz! Some suggestions from my side:
- Isn't this algorithm contributed by Brockmann? I suppose Sentinel Hub is a leftover from the template you used. 
- "Open Notebook" should either have a real link or be removed.
- "License" should either have a real link or be removed.
- Pricing information would be great.

**Comment by Schpidi** [comment]
Tested it locally and the `index.ndjson` is still working. Thus I'm going to merge it to test integration with the marketplace.

**Comment by Schpidi** [comment]
Seems like something didn't quite work with the automatic deploy. Maybe a side effect of the almost simultaneous other PR? Anyway, could you maybe investigate what happened @dthiex? Thanks

**Comment by Dorothyrono** [comment]
it should be deployed now

 The deployed page can be found be found here meanwhile  https://s3.eu-central-1.amazonaws.com/collections.eurodatacube.com/mci/index.html    

somehow the empty resources metadata wansn't acceptable .

**Pull request merged**
